CREATE USER IF NOT EXISTS "DEV" SALT 'cb14b3fa4d7ce4e3' HASH 'c3dc75954b0e747033af75eaa84c4a4348177b311f73d3b56eb394a445a5819e' ADMIN;
CREATE SCHEMA IF NOT EXISTS "LISTADO" AUTHORIZATION "DEV";
CREATE CACHED TABLE IF NOT EXISTS "LISTADO"."ALUMNO"(
    "LEGAJO" INTEGER NOT NULL,
    "CARRERA" VARCHAR(255) NOT NULL,
    "NOMBRE" VARCHAR(255) NOT NULL
);
ALTER TABLE "LISTADO"."ALUMNO" ADD CONSTRAINT IF NOT EXISTS "LISTADO"."CONSTRAINT_7" PRIMARY KEY("LEGAJO");
-- 0 +/- SELECT COUNT(*) FROM LISTADO.ALUMNO;
CREATE CACHED TABLE IF NOT EXISTS "LISTADO"."MATERIA"(
    "ID" INTEGER NOT NULL,
    "ANIO" INTEGER NOT NULL,
    "CALIFICACION" INTEGER NOT NULL,
    "CREDITOS" DOUBLE NOT NULL,
    "ESTADO" VARCHAR(255) NOT NULL,
    "HORAS_SEMANALES" INTEGER NOT NULL,
    "NOMBRE" VARCHAR(255) NOT NULL,
    "PERIODO" VARCHAR(255) NOT NULL,
    "TIPO" VARCHAR(255) NOT NULL
);
ALTER TABLE "LISTADO"."MATERIA" ADD CONSTRAINT IF NOT EXISTS "LISTADO"."CONSTRAINT_5" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM LISTADO.MATERIA;
CREATE CACHED TABLE IF NOT EXISTS "LISTADO"."MATERIA_MATERIA"(
    "ID" INTEGER NOT NULL,
    "CORRELATIVAS_ID" INTEGER NOT NULL
);
ALTER TABLE "LISTADO"."MATERIA_MATERIA" ADD CONSTRAINT IF NOT EXISTS "LISTADO"."CONSTRAINT_9" PRIMARY KEY("ID", "CORRELATIVAS_ID");
-- 0 +/- SELECT COUNT(*) FROM LISTADO.MATERIA_MATERIA;
ALTER TABLE "LISTADO"."MATERIA_MATERIA" ADD CONSTRAINT IF NOT EXISTS "LISTADO"."FKCER63KLN4P3BLJDC4228UON0R" FOREIGN KEY("CORRELATIVAS_ID") REFERENCES "LISTADO"."MATERIA"("ID") NOCHECK;
ALTER TABLE "LISTADO"."MATERIA_MATERIA" ADD CONSTRAINT IF NOT EXISTS "LISTADO"."FKN0S7JEVFX3IPT59XNVL39VGXP" FOREIGN KEY("ID") REFERENCES "LISTADO"."MATERIA"("ID") NOCHECK;
CREATE CACHED TABLE IF NOT EXISTS "LISTADO"."CONFIG" (
	"PARAMETRO" VARCHAR(30) NOT NULL,
	"VALOR" VARCHAR(20) NOT NULL,
	"TIPO" VARCHAR(20) NOT NULL
);
ALTER TABLE "LISTADO"."CONFIG" ADD CONSTRAINT IF NOT EXISTS "LISTADO"."CONSTRAIT_11" PRIMARY KEY("PARAMETRO");
-- 0 +/- SELECT COUNT(*) FROM LISTADO.CONFIG;
